from datetime import datetime
import os


def run(target):

    print("========== REPORT ==========\n")

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    os.makedirs("reports", exist_ok=True)

    filename = f"reports/{target.original}_{timestamp}.txt"

    with open(filename, "w") as report:

        report.write("=" * 60 + "\n")
        report.write("                 EDITH RECON REPORT\n")
        report.write("=" * 60 + "\n\n")

        report.write(f"Target           : {target.original}\n")
        report.write(f"IP Address       : {target.ip}\n")
        report.write(f"Hostname         : {target.reverse_dns}\n\n")

        report.write("=" * 60 + "\n")
        report.write("WHOIS\n")
        report.write("=" * 60 + "\n")

        report.write(f"Registrar        : {target.registrar}\n")
        report.write(f"Creation Date    : {target.creation_date}\n")
        report.write(f"Expiration Date  : {target.expiration_date}\n\n")

        report.write("=" * 60 + "\n")
        report.write("OPEN PORTS\n")
        report.write("=" * 60 + "\n")

        if target.open_ports:

            for port in target.open_ports:

                report.write(
                    f"{port['port']}/{port['protocol']} ({port['service']})\n"
                )

        else:

            report.write("No Open Ports Found\n")

        report.write("\n")

        report.write("=" * 60 + "\n")
        report.write("BANNER\n")
        report.write("=" * 60 + "\n")

        report.write(f"HTTP Response : {target.banner}\n")
        report.write(f"Server        : {target.server}\n\n")

        report.write("=" * 60 + "\n")
        report.write("SSL\n")
        report.write("=" * 60 + "\n")

        report.write(f"Common Name : {target.ssl_subject}\n")
        report.write(f"Issuer      : {target.ssl_issuer}\n")
        report.write(f"Expires On  : {target.ssl_expiry}\n\n")

        report.write("=" * 60 + "\n")
        report.write("SUBDOMAINS\n")
        report.write("=" * 60 + "\n")

        if target.subdomains:

            for index, sub in enumerate(target.subdomains, start=1):

                report.write(
                    f"{index}. {sub['hostname']} ({sub['ip']})\n"
                )

        else:

            report.write("No Subdomains Found\n")

        report.write("\n")

        report.write("=" * 60 + "\n")
        report.write("SUMMARY\n")
        report.write("=" * 60 + "\n")

        report.write(f"Open Ports  : {len(target.open_ports)}\n")
        report.write(f"Subdomains  : {len(target.subdomains)}\n\n")

        report.write("=" * 60 + "\n")
        report.write("Generated by EDITH Recon v1.0.0\n")
        report.write("=" * 60 + "\n")

    print("[+] Report Generated Successfully")
    print(f"[+] Saved To : {filename}\n")