from datetime import datetime
import os


def run(target):

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    os.makedirs("reports", exist_ok=True)

    filename = f"reports/{target.original}_{timestamp}.html"

    hostname = target.reverse_dns if target.reverse_dns else "Not Available"

    html = f"""
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">

<title>EDITH Recon Report</title>

<style>

body {{
    font-family: Arial, sans-serif;
    background: #f4f6f8;
    margin: 40px;
}}

.container {{
    max-width: 1000px;
    margin: auto;
    background: white;
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0px 0px 10px rgba(0,0,0,.15);
}}

h1 {{
    text-align:center;
    color:#0d6efd;
}}

h2 {{
    color:#0d6efd;
    border-bottom:2px solid #0d6efd;
    padding-bottom:5px;
}}

table {{
    width:100%;
    border-collapse:collapse;
    margin-top:10px;
}}

table th,
table td {{

    border:1px solid #ddd;
    padding:10px;
}}

table th {{

    background:#0d6efd;
    color:white;
}}

.success {{

    color:green;
    font-weight:bold;
}}

.footer {{

    text-align:center;
    margin-top:40px;
    color:gray;
}}

</style>

</head>

<body>

<div class="container">

<h1>EDITH Recon Report v1.1</h1>

<h2>Target Information</h2>

<table>

<tr><th>Field</th><th>Value</th></tr>

<tr><td>Target</td><td>{target.original}</td></tr>

<tr><td>IP Address</td><td>{target.ip}</td></tr>

<tr><td>Hostname</td><td>{hostname}</td></tr>

<tr><td>Date</td><td>{datetime.now().strftime("%d-%m-%Y")}</td></tr>

<tr><td>Time</td><td>{datetime.now().strftime("%H:%M:%S")}</td></tr>

</table>

<h2>WHOIS</h2>

<table>

<tr><th>Registrar</th><th>Creation</th><th>Expiry</th></tr>

<tr>

<td>{target.registrar}</td>

<td>{target.creation_date}</td>

<td>{target.expiration_date}</td>

</tr>

</table>

<h2>Open Ports</h2>

<table>

<tr>

<th>Port</th>

<th>Protocol</th>

<th>Service</th>

</tr>
"""

    for port in target.open_ports:

        html += f"""
<tr>

<td>{port['port']}</td>

<td>{port['protocol']}</td>

<td>{port['service']}</td>

</tr>
"""

    html += """

</table>

<h2>Banner</h2>

<table>

<tr><th>HTTP Response</th><th>Server</th></tr>

"""

    html += f"""

<tr>

<td>{target.banner}</td>

<td>{target.server}</td>

</tr>

"""

    html += """

</table>

<h2>SSL</h2>

<table>

<tr>

<th>Common Name</th>

<th>Issuer</th>

<th>Expiry</th>

</tr>

"""

    html += f"""

<tr>

<td>{target.ssl_subject}</td>

<td>{target.ssl_issuer}</td>

<td>{target.ssl_expiry}</td>

</tr>

"""

    html += """

</table>

<h2>Subdomains</h2>

<table>

<tr>

<th>#</th>

<th>Hostname</th>

<th>IP Address</th>

</tr>

"""

    for index, sub in enumerate(target.subdomains, start=1):

        html += f"""

<tr>

<td>{index}</td>

<td>{sub['hostname']}</td>

<td>{sub['ip']}</td>

</tr>

"""

    html += f"""

</table>

<h2>Summary</h2>

<table>

<tr><th>Metric</th><th>Value</th></tr>

<tr><td>Open Ports</td><td>{len(target.open_ports)}</td></tr>

<tr><td>Subdomains</td><td>{len(target.subdomains)}</td></tr>

<tr><td>Status</td><td class="success">SUCCESS</td></tr>

</table>

<div class="footer">

Generated by <b>EDITH Recon v1.1.0</b>

</div>

</div>

</body>

</html>

"""

    with open(filename, "w", encoding="utf-8") as file:

        file.write(html)

    print("[+] HTML Report Generated Successfully")
    print(f"[+] Saved To : {filename}\n")