import os
import time

from colorama import Fore, Style, init

init(autoreset=True)


def clear():
    os.system("cls" if os.name == "nt" else "clear")


def show_banner():
    clear()

    print(Fore.CYAN + r"""
   ███████╗██████╗ ██╗████████╗██╗  ██╗
   ██╔════╝██╔══██╗██║╚══██╔══╝██║  ██║
   █████╗  ██║  ██║██║   ██║   ███████║
   ██╔══╝  ██║  ██║██║   ██║   ██╔══██║
   ███████╗██████╔╝██║   ██║   ██║  ██║
   ╚══════╝╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝
""" + Style.RESET_ALL)

    print(Fore.WHITE + Style.BRIGHT + "              E D I T H   R E C O N")
    print(Fore.LIGHTBLACK_EX + "       Network Recon & Intelligence Toolkit")
    print()
    print(Fore.YELLOW + "                    v1.0.0")
    print(Fore.GREEN + "                  by Aliraza")
    print()

    print(Fore.CYAN + "══════════════════════════════════════════════════════════════")
    print()

    modules = [
        "Initializing EDITH",
        "Loading Core Engine",
        "Loading DNS Module",
        "Loading WHOIS Module",
        "Loading Port Scanner",
        "Loading Banner Engine",
        "Loading Report Generator",
    ]

    for module in modules:
        print(Fore.YELLOW + f"[*] {module}...", end="", flush=True)
        time.sleep(0.35)
        print(Fore.GREEN + " ✓")

    print()
    print(Fore.GREEN + Style.BRIGHT + "[+] System Status : READY")
    print(Fore.CYAN + "══════════════════════════════════════════════════════════════")
    print()

    time.sleep(0.5)



def show_footer():

    print()
    print(Fore.CYAN + "═" * 62)
    print()

    print(Fore.GREEN + Style.BRIGHT + "[✓] Scan Completed Successfully")
    print(Fore.LIGHTBLACK_EX + "Generated by EDITH RECON v1.0.0")
    print(Fore.WHITE + "Thank you for using EDITH.")
    print(Fore.LIGHTBLACK_EX + "Stay Curious. Stay Ethical.")

    print()
    print(Fore.CYAN + "═" * 62)